#!/usr/bin/env python3
"""SEDI-PRV-02 (predicate-only disclosure) in ProVerif.

Usage:
    python3 scripts/prv02_proverif.py            # generate + run all
    python3 scripts/prv02_proverif.py --only NEG_
    python3 scripts/prv02_proverif.py --list
    python3 scripts/prv02_proverif.py --generate

Writes  proverif/prv02/<config>__{eq,trace,link}.pv
        results/prv02/..., summary.md, results.json

Mechanism modelled (keripy tests/acdc/test_bulk_issuance.py, sedi-age): the
issuer precomputes one boolean flag per predicate in a bounded domain and
signs an aggregate of SALTED flag digests plus a salted digest of the date of
birth. To answer predicate p the holder reveals flag p and its salt; every
other flag, and the date of birth, stays behind its salted digest. There are
no zero-knowledge range proofs: only precomputed predicates can be answered.

Predicate domain: age>=18, >=21, >=25, >=30.
Two attribute worlds (choice[L, R]):
    x0 = age 22 (left)    x1 = age 27 (right)
They give the same answer on >=18 (T), >=21 (T) and >=30 (F) -- the
predicates the holder approves -- and differ only on >=25 (F vs T), which
the holder never approves. The date of birth differs too.

Metadata is symbolic: every response and error carries (size class,
timing class). A negative variant makes one of them a function of the
hidden answer to >=25. THIS IS AN ABSTRACTION: a symbolic result about
abstract metadata fields does not establish constant-time or constant-size
behaviour of a real implementation.

Three models per configuration:
  __eq     x0 vs x1 in one holder: lemmas 1 (Boolean-only), 2 (metadata),
           4 (repeated queries), 5 (errors)
  __trace  world x0 with events: lemma 3 (holder authorization), date-of-
           birth secrecy, sanity
  __link   lemma 6: population {H1, H2}; world 0: H1 answers V1 and V2,
           world 1: H1 answers V1, H2 answers V2
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "proverif" / "prv02"
RESULTS = ROOT / "results" / "prv02"

PREDS = ["p18", "p21", "p25", "p30"]
# answers for age 22 (x0) and 27 (x1)
ANSWER = {"p18": ("T", "T"), "p21": ("T", "T"), "p25": ("F", "T"), "p30": ("F", "F")}
APPROVED = ["p18", "p21", "p30"]

H, F = "holds", "fails"
CONFIGS = [
    dict(id="POS_baseline", desc="holder approves {>=18, >=21, >=30}; fresh bulk copy per response; "
         "uniform size, timing and errors", flags=[],
         exp=dict(EQ=H, AUTH=H, DOB=H, SANITY=H, LINK=H)),
    dict(id="NEG_size_depends_on_x", desc="response size class depends on the hidden answer to >=25",
         flags=["SIZE"], exp=dict(EQ=F, AUTH=H, DOB=H, SANITY=H, LINK=H)),
    dict(id="NEG_timing_depends_on_x", desc="timing class depends on the hidden answer to >=25",
         flags=["TIMING"], exp=dict(EQ=F, AUTH=H, DOB=H, SANITY=H, LINK=H)),
    dict(id="NEG_error_depends_on_x", desc="refusing >=25 says 'not satisfied' vs 'declined' "
         "depending on the answer", flags=["ERROR"], exp=dict(EQ=F, AUTH=H, DOB=H, SANITY=H, LINK=H)),
    dict(id="NEG_arbitrary_predicates", desc="holder approves whatever predicate the verifier asks",
         flags=["ARBITRARY"], exp=dict(EQ=F, AUTH=H, DOB=H, SANITY=H, LINK=H)),
    dict(id="NEG_no_holder_authorization", desc="wallet answers any request without holder approval",
         flags=["NOAUTH"], exp=dict(EQ=F, AUTH=F, DOB=H, SANITY=H, LINK=H)),
    dict(id="NEG_stable_proof_id", desc="one credential copy (one aggregate) reused for every response",
         flags=["STABLE"], exp=dict(EQ=H, AUTH=H, DOB=H, SANITY=H, LINK=F)),
]

PRELUDE = """(* GENERATED by scripts/prv02_proverif.py -- do not edit by hand.
   SEDI-PRV-02 {cid} [{mode}]: {desc}
   Metadata fields are SYMBOLIC abstractions of size / timing / error
   behaviour; they say nothing about a real implementation. *)

free c: channel.
free copych, copych1, copych2: channel [private].

fun h(bitstring): bitstring.
fun pk(bitstring): bitstring.
fun sign(bitstring, bitstring): bitstring.
fun verify(bitstring, bitstring, bitstring): bool
  reduc forall m: bitstring, k: bitstring; verify(sign(m, k), m, pk(k)) = true
  otherwise forall x: bitstring, y: bitstring, z: bitstring; verify(x, y, z) = false.

(* public functions an implementation might (wrongly) make observable *)
fun sizeclass(bitstring): bitstring.
fun timeclass(bitstring): bitstring.
fun errcode(bitstring): bitstring.

const p18, p21, p25, p30, T, F: bitstring.
const req, resp, err, std, declined, hH, hH1, hH2: bitstring.

event PredicateRequested(bitstring, bitstring, bitstring).
event HolderApprovedPredicate(bitstring, bitstring).
event PredicateResponse(bitstring, bitstring, bitstring, bitstring).
event ErrorResponse(bitstring, bitstring, bitstring).
event TimingClass(bitstring, bitstring, bitstring).
event ResponseSize(bitstring, bitstring, bitstring).
"""


def flags_let(world, mode, suffix=""):
    """Flag values b_p. world 'eq': choice where x0/x1 differ."""
    out = []
    for p in PREDS:
        a0, a1 = ANSWER[p]
        if mode == "eq" and a0 != a1:
            out.append(f"  let b{p[1:]}{suffix} = choice[{a0}, {a1}] in\n")
        else:
            out.append(f"  let b{p[1:]}{suffix} = {a0} in\n")
    return "".join(out)


def copy_generator(chan, dob, suffix=""):
    """Issuer mints a copy: salted flag digests + salted DOB digest, signed."""
    salts = " ".join(f"new s{p[1:]}: bitstring;" for p in PREDS)
    digs = "".join(f"  let d{p[1:]} = h(({p}, b{p[1:]}{suffix}, s{p[1:]})) in\n" for p in PREDS)
    return (f"  {salts} new sd: bitstring;\n{digs}"
            f"  let dd = h(({dob}, sd)) in\n"
            f"  let ag = h((d18, d21, d25, d30, dd)) in\n"
            f"  out({chan}, (ag, sign(ag, skI), s18, s21, s25, s30, dd))\n")


def responder(cfg, mode, p, chan, holder, suffix=""):
    """Holder answers predicate p from a copy received on chan."""
    f = set(cfg["flags"])
    n = p[1:]
    others = [q[1:] for q in PREDS if q != p]
    size = "sizeclass(b25%s)" % suffix if "SIZE" in f else "std"
    tim = "timeclass(b25%s)" % suffix if "TIMING" in f else "std"
    meta = f"({size}, {tim})"
    others_d = ", ".join(f"h(({'p' + q}, b{q}{suffix}, s{q}))" for q in others)
    approve = "" if "NOAUTH" in f else f"event HolderApprovedPredicate({holder}, {p}); "
    ev = ""
    if mode == "trace":
        ev = (f"event PredicateRequested(v, {holder}, {p}); {approve}"
              f"event PredicateResponse(v, {p}, b{n}{suffix}, {meta}); "
              f"event TimingClass(v, {p}, {tim}); event ResponseSize(v, {p}, {size}); ")
    return (f"  !( in(c, (=req, v: bitstring, ={p}));\n"
            f"     in({chan}, (ag: bitstring, sag: bitstring, s18: bitstring, s21: bitstring, "
            f"s25: bitstring, s30: bitstring, dd: bitstring));\n"
            f"     {ev}out(c, (resp, v, {p}, b{n}{suffix}, s{n}, ({others_d}), dd, ag, sag, {meta})) )\n")


def refuser(cfg, mode, p, holder, suffix=""):
    f = set(cfg["flags"])
    code = f"errcode(b{p[1:]}{suffix})" if "ERROR" in f else "declined"
    ev = f"event ErrorResponse(v, {code}, (std, std)); " if mode == "trace" else ""
    return f"  !( in(c, (=req, v: bitstring, ={p})); {ev}out(c, (err, v, {p}, {code}, (std, std))) )\n"


def holder_procs(cfg, mode, chan, holder, suffix=""):
    f = set(cfg["flags"])
    answered = PREDS if ({"ARBITRARY", "NOAUTH"} & f) else APPROVED
    parts = [responder(cfg, mode, p, chan, holder, suffix) for p in answered]
    parts += [refuser(cfg, mode, p, holder, suffix) for p in PREDS if p not in answered]
    return parts


def copies(cfg, chan, dob, suffix=""):
    """Bulk: a fresh copy per response. STABLE: one copy, reused."""
    gen = copy_generator(chan, dob, suffix)
    if "STABLE" in cfg["flags"]:
        # mint once, then serve the same copy forever
        body = gen.replace(f"out({chan}, ", f"!out({chan}, ")
        return "  (\n" + body + "  )\n"
    return "  !(\n" + gen + "  )\n"


def eq_or_trace(cfg, mode):
    lines = [PRELUDE.format(cid=cfg["id"], mode=mode, desc=cfg["desc"])]
    if mode == "trace":
        lines += [
            "query v, p, b, m: bitstring; event(PredicateResponse(v, p, b, m)) ==> "
            "event(HolderApprovedPredicate(hH, p)).  (* L3 holder authorization *)\n",
            "query attacker(new dob0).  (* L1 the date of birth itself is never disclosed *)\n",
            "query v, p, b, m: bitstring; event(PredicateResponse(v, p, b, m)).  "
            "(* sanity: a response is produced *)\n"]
    lines.append("process\n  new skI: bitstring;\n  out(c, pk(skI));\n"
                 "  new dob0: bitstring; new dob1: bitstring;\n")
    lines.append("  let dob = choice[dob0, dob1] in\n" if mode == "eq" else "  let dob = dob0 in\n")
    lines.append(flags_let("x", mode))
    parts = [copies(cfg, "copych", "dob")] + holder_procs(cfg, mode, "copych", "hH")
    lines.append("  (\n" + "  |\n".join(parts) + "  )\n")
    return "".join(lines)


def mint(tag, dob, suffix):
    """Let-bindings for one issuer-signed copy named by tag."""
    out = "".join(f"  new s{p[1:]}{tag}: bitstring;\n" for p in PREDS)
    out += f"  new sd{tag}: bitstring;\n"
    out += "".join(f"  let d{p[1:]}{tag} = h(({p}, b{p[1:]}{suffix}, s{p[1:]}{tag})) in\n" for p in PREDS)
    out += f"  let dd{tag} = h(({dob}, sd{tag})) in\n"
    out += (f"  let ag{tag} = h((d18{tag}, d21{tag}, d25{tag}, d30{tag}, dd{tag})) in\n"
            f"  let sag{tag} = sign(ag{tag}, skI) in\n")
    return out


def link_response(cfg, tag, suffix):
    """Answer >=21 from copy `tag` (terms may contain choice)."""
    f = set(cfg["flags"])
    size = f"sizeclass(b25{suffix})" if "SIZE" in f else "std"
    tim = f"timeclass(b25{suffix})" if "TIMING" in f else "std"
    return (f"  ( in(c, (=req, v: bitstring, =p21));\n"
            f"    out(c, (resp, v, p21, b21{suffix}, s21{tag}, (d18{tag}, d25{tag}, d30{tag}), "
            f"dd{tag}, ag{tag}, sag{tag}, ({size}, {tim}))) )\n")


def link_model(cfg):
    """Population {H1, H2}, both age 22 (same answer on every predicate).
    world 0: H1 answers V1 and V2; world 1: H1 answers V1, H2 answers V2.
    The world difference is in the copy CONTENT (choice), never in a private
    channel, so ProVerif compares only what the verifiers can observe."""
    lines = [PRELUDE.format(cid=cfg["id"], mode="link", desc=cfg["desc"])]
    lines.append("process\n  new skI: bitstring;\n  out(c, pk(skI));\n"
                 "  new dob1: bitstring; new dob2: bitstring;\n")
    lines.append(flags_let("x", "trace", ""))      # H1 and H2 have the same flags
    if "STABLE" in cfg["flags"]:
        # each holder owns ONE copy; presentation 2 reuses H1's copy in world 0
        lines.append(mint("A", "dob1", "") + mint("B", "dob2", ""))
        for n in ("s18", "s21", "s25", "s30", "sd", "d18", "d21", "d25", "d30", "dd", "ag", "sag"):
            lines.append(f"  let {n}Q = choice[{n}A, {n}B] in\n")
        second = "Q"
    else:
        # bulk: every response uses a freshly minted copy of its holder
        lines.append(mint("A", "dob1", ""))
        lines.append("  let dobQ = choice[dob1, dob2] in\n" + mint("Q", "dobQ", ""))
        second = "Q"
    parts = [link_response(cfg, "A", ""), link_response(cfg, second, "")]
    lines.append("  (\n" + "  |\n".join(parts) + "  )\n")
    return "".join(lines)


# ---------------------------------------------------------------------------

def find_proverif(explicit):
    for cand in (explicit, shutil.which("proverif"),
                 os.path.expanduser("~/opt/proverif2.05/proverif")):
        if cand and os.path.isfile(cand) and os.access(cand, os.X_OK):
            return cand
    sys.exit("proverif not found: pass --proverif PATH or put it on PATH")


def summary_lines(out):
    if "Verification summary:" not in out:
        return []
    return [ln.strip() for ln in out.split("Verification summary:")[1].splitlines()
            if ln.strip().startswith(("Query ", "Observational"))]


def test_line(out):
    lines = out.splitlines()
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].startswith("The attacker tests whether"):
            return " ".join(ln.strip() for ln in lines[i:i + 4])
    return ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default="")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--generate", action="store_true")
    ap.add_argument("--timeout", type=int, default=600)
    ap.add_argument("--proverif", default=None)
    args = ap.parse_args()

    cfgs = [c for c in CONFIGS if c["id"].startswith(args.only)]
    if args.list:
        for c in cfgs:
            print(f"{c['id']:30} {c['desc']}")
        return 0
    MODELS.mkdir(parents=True, exist_ok=True)
    for c in cfgs:
        (MODELS / f"{c['id']}__eq.pv").write_text(eq_or_trace(c, "eq"))
        (MODELS / f"{c['id']}__trace.pv").write_text(eq_or_trace(c, "trace"))
        (MODELS / f"{c['id']}__link.pv").write_text(link_model(c))
    if args.generate:
        print(f"wrote {3 * len(cfgs)} models to {MODELS.relative_to(ROOT)}")
        return 0

    pv = find_proverif(args.proverif)
    RESULTS.mkdir(parents=True, exist_ok=True)

    def run(name):
        try:
            p = subprocess.run([pv, str(MODELS / f"{name}.pv")], capture_output=True,
                               text=True, timeout=args.timeout)
            out = p.stdout + p.stderr
        except subprocess.TimeoutExpired:
            out = "TIMEOUT"
        (RESULTS / f"{name}.log").write_text(out)
        return out

    def equiv(out):
        if "RESULT Observational equivalence is true" in out:
            return H
        if "RESULT Observational equivalence cannot be proved" in out:
            return F if "A trace has been found" in out else "unknown"
        return "error"

    records, mismatches = [], 0
    for c in cfgs:
        got, tests = {}, {}
        for mode, key in (("eq", "EQ"), ("link", "LINK")):
            out = run(f"{c['id']}__{mode}")
            got[key] = equiv(out)
            tests[key] = test_line(out) if got[key] == F else ""
        res = summary_lines(run(f"{c['id']}__trace"))
        if len(res) == 3:
            got["AUTH"] = "unknown" if "cannot" in res[0] else (H if res[0].endswith("is true.") else F)
            got["DOB"] = "unknown" if "cannot" in res[1] else (H if res[1].endswith("is true.") else F)
            got["SANITY"] = H if res[2].endswith("is false.") else F
        else:
            got.update(AUTH="error", DOB="error", SANITY="error")
        bad = [k for k in c["exp"] if got[k] != c["exp"][k]]
        mismatches += len(bad)
        records.append(dict(id=c["id"], description=c["desc"], flags=c["flags"],
                            expected=c["exp"], actual=got, mismatches=bad, tests=tests))
        print(f"{c['id']:30} " + " ".join(f"{k}={got[k]:5}" for k in c["exp"])
              + ("" if not bad else "   MISMATCH: " + ",".join(bad)), flush=True)

    ver = subprocess.run([pv, "-help"], capture_output=True, text=True).stdout.splitlines()[0]
    (RESULTS / "results.json").write_text(json.dumps(
        dict(proverif=ver, generated=time.strftime("%Y-%m-%dT%H:%M:%S"),
             mismatches=mismatches, results=records), indent=1))
    keys = ["EQ", "AUTH", "DOB", "LINK", "SANITY"]
    names = ["x0 ≡ x1 (L1,L2,L4,L5)", "L3 holder auth", "L1 DOB secret", "L6 no stable id", "sanity"]
    lines = [f"# PRV-02 ProVerif results ({ver})", "",
             "| config | " + " | ".join(names) + " |", "|---|" + "---|" * len(names)]
    for r in records:
        lines.append(f"| {r['id']} | " + " | ".join(
            ("holds" if r["actual"][k] == H else "**FAILS**" if r["actual"][k] == F else r["actual"][k])
            + ("" if r["actual"][k] == r["expected"][k] else " ✗") for k in keys) + " |")
    (RESULTS / "summary.md").write_text("\n".join(lines) + "\n")
    print(f"\n{mismatches} mismatch(es)")
    return 1 if mismatches else 0


if __name__ == "__main__":
    sys.exit(main())
